# Generated by Django 4.0.10 on 2026-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.IntegerField()),
                ('workbookname', models.CharField(max_length=50)),
                ('worksheetname', models.CharField(max_length=50)),
                ('studentnumber', models.CharField(max_length=10)),
                ('inserttimestamp', models.DateTimeField(auto_now_add=True)),
                ('computername', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'session_stream',
                'managed': False,
            },
        ),
    ]
