# Generated by Django 4.0.10 on 2026-01-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersTable',
            fields=[
                ('answerid', models.BigAutoField(primary_key=True, serialize=False)),
                ('questionid', models.CharField(max_length=50)),
                ('answertext', models.TextField()),
            ],
            options={
                'db_table': 'answers_stream',
                'managed': False,
            },
        ),
    ]
