# Generated by Django 6.0.2 on 2026-02-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_answerstable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mytable',
            table='sessions',
        ),
    ]
