# Helper to check if text is a noun phrase (not a clause/sentence)
def is_noun_phrase(text):
  doc = get_nlp()(text)
  roots = [token for token in doc if token.head == token]
  if not roots:
    return False
  root = roots[0]
  # Acceptable roots for noun phrases: NOUN, PROPN, ADJ
  return root.pos_ in ("NOUN", "PROPN", "ADJ")
# Detects if a clause is of the form 'there is ...'

def is_there_is_clause(text):
  doc = nlp(text)
  # Helper to check synonymy for 'there'
  def is_syn_with_there(token):
    from nltk.corpus import wordnet
    lemma = token.lemma_.lower()
    if lemma == 'there':
      return True
    for syn in wordnet.synsets('there'):
      if lemma in [l.lower() for l in syn.lemma_names()]:
        return True
    return False

  for token in doc:
    if token.dep_ == 'ROOT':
      has_expl_there = False
      has_attr = False
      for child in token.children:
        if child.dep_ == 'expl' and is_syn_with_there(child):
          has_expl_there = True
        if child.dep_ == 'attr':
          has_attr = True
      if has_expl_there and has_attr:
        return True
  return False
# Alternative, more elegant equative clause detector
def is_equative2(clause):
  doc = nlp(clause)
  # Helper to check synonymy
  def is_syn_with(token_text, *targets):
    from nltk.corpus import wordnet
    for target in targets:
      for syn in wordnet.synsets(target):
        if token_text.lower() in [lemma.lower() for lemma in syn.lemma_names()]:
          return True
    return False

  for token in doc:
    # Look for ROOT token synonymous with 'is'
    #print(f"Checking token '{token.text}' with dep '{token.dep_}' against 'is'")
    if (token.dep_ == 'ROOT' and is_syn_with(token.lemma_, 'is')) or (token.dep_ == 'ROOT' and is_syn_with(token.lemma_, 'represents')):
      #print(f"Found potential equative ROOT: '{token.text}' (lemma: '{token.lemma_}')")
      # Look for immediate child with dep_ == 'attr'
      for child in token.children:
        # If ROOT is 'is' (aux), look for 'attr' child; if ROOT is 'represent', look for 'dobj' child
        if (
            (is_syn_with(token.lemma_, 'is') and child.dep_ == 'attr' and is_syn_with(child.lemma_, 'proportion', 'percentage', 'percent'))
            or
            (is_syn_with(token.lemma_, 'represent') and child.dep_ == 'dobj' and is_syn_with(child.lemma_, 'proportion', 'percentage', 'percent'))
        ):
          #print(f"Found potential equative child: '{child.text}' with dep '{child.dep_}'")
          # Check for child with dep_ == 'relcl'
          for grandchild in child.children:
            if grandchild.dep_ == 'relcl':
              return True
            # Check for child with dep_ == 'prep' leading to 'pobj' then 'relcl'
            if grandchild.dep_ == 'prep':
              for g2 in grandchild.children:
                if g2.dep_ == 'pobj':
                  for g3 in g2.children:
                    if g3.dep_ == 'relcl':
                      return True
                    # One more level down: prep > pobj > prep > pobj > relcl
                    if g3.dep_ == 'prep':
                      for g4 in g3.children:
                        if g4.dep_ == 'pobj':
                          for g5 in g4.children:
                            if g5.dep_ == 'relcl':
                              return True
  return False
# -*- coding: utf-8 -*-
"""Copy of pandas_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U10dx4ZUnWwQ74ShCEYBuaZq0DgZqHcO

**Install packages**
"""

import nltk
import spacy


from nltk.corpus import wordnet
from spacy import displacy

# Global NLP model cache - load once, reuse everywhere
_NLP_MODEL = None

def get_nlp():
    """Get cached NLP model, loading only once."""
    global _NLP_MODEL
    if _NLP_MODEL is None:
        _NLP_MODEL = spacy.load("en_core_web_trf")
        print("⚙️  Loaded spaCy model once (cached for all submissions)")
    return _NLP_MODEL

nlp = get_nlp()

"""# Load parsing routines"""
def show_chunks(text):
  doc = get_nlp()(text)
  for chunk in doc.noun_chunks:
    print(chunk.text, chunk.root.text, chunk.root.dep_,
          chunk.root.head.text)
def print_pic(text):
  doc = get_nlp()(text)
  import webbrowser
  from pathlib import Path
  html = displacy.render(doc, style="dep")
  out_path = Path.cwd() / "dep_parse.html"
  out_path.write_text(html, encoding="utf-8")

  #print(f"✓ Wrote visualization to: {out_path.absolute()}")
  #print(f"  File size: {len(html)} bytes")
  #print(f"  Opening in browser...")

  webbrowser.open(out_path.as_uri())
def print_chunks_pic(text):
  get_nlp().add_pipe("merge_noun_chunks", last=True)
  doc = get_nlp()(text)
  import webbrowser
  from pathlib import Path
  html = displacy.render(doc, style="dep")
  out_path = Path.cwd() / "dep_chunks_parse.html"
  out_path.write_text(html, encoding="utf-8")
  print(f"Wrote {out_path} ({len(html)} bytes)")
  webbrowser.open(out_path.as_uri())
  #handle equative clases like "X is the proportion of Y that Z" vs non-equative like "X of Y is Z"
  #as well as "X represents the proportion of Y that Z"

def rearrange_noun_phrase(noun_phrase):
#moves preposition phrase to back from front
  noun_tokens = get_nlp()(noun_phrase)
  return_phrase =''
  root_pos = 0
  word2add =''
  for token in noun_tokens:
    if token.head.dep_ == 'ROOT' and token.dep_ == 'pobj' and token.pos_ == 'NOUN' or token.dep_ =='ROOT' and token.i>0:
      root_pos = token.i

  if root_pos > 0:
    for pos in range(root_pos-1, len(noun_tokens)):
      return_phrase = return_phrase + ' ' + noun_tokens[pos].text
  else:
    return_phrase = noun_phrase

  if root_pos > 1:
    for pos in range(0,root_pos-1):
      if pos == 0:
        word2add = noun_tokens[pos].text.lower()
      else:
        word2add = noun_tokens[pos].text
      return_phrase = return_phrase + ' ' + word2add
  return return_phrase

# takes a noun phrase Span and extracts prepositional phrases following the head noun
# for example "the proportion of people" becomes "people"
def get_base_simple(noun_phrase_span, head_noun_token):
  """
  Extract prepositional phrases from an already-tokenized spaCy Span.
  
  Args:
    noun_phrase_span: A spaCy Span object (not a string)
  
  Logic flow:
  1. Work directly with the passed-in Span's tokens
  2. Find the ROOT token and iterate through its children
  3. Collect left and right edges of prepositional children
  4. Return the slice of tokens spanning from min left edge to max right edge
  5. If no prepositional phrases exist, return the entire span
  6. No re-tokenization - preserves original dependencies
  """
  
  try:
    # Validate input is a Span
    if not noun_phrase_span or len(noun_phrase_span) == 0:
      return noun_phrase_span
    
    l_edges = set()
    r_edges = set()
    
    # Work directly with the span's tokens (no re-tokenization)
    for token in noun_phrase_span:
      # find the root of the noun phrase
      if token == head_noun_token:
        # Check direct children for prepositions
        for child in token.children:
            if child.dep_ == 'prep':
                # Get the full span EXCLUDING the preposition itself, but INCLUDING all descendants
                l_edges.add(child.left_edge.i + 1)  # Skip the preposition token
                r_edges.add(child.right_edge.i + 1)  # Include all descendants
    
    # Extract min and max boundaries
    the_min = min(l_edges) if l_edges else noun_phrase_span.start
    the_max = max(r_edges) if r_edges else noun_phrase_span.end
    
    # Return span slice - use the document to create the span
    return noun_phrase_span.doc[the_min:the_max] if l_edges else noun_phrase_span
    
  except Exception as e:
    print(f"Error in get_base_simple: {str(e)}")
    # Return original span as fallback
    return noun_phrase_span

# is it of the form 'the noun phrase is A' or 'A is the noun phrase?
def is_encrypting(clause):
  dec_encrypt = False
  if is_equative2(clause)==True:
    clause_tokens = get_nlp()(clause)
    for token in clause_tokens:
      if (token.dep_ == 'attr' and token.head.dep_ == 'ROOT') or (token.dep_ == 'dobj' and token.head.dep_ == 'ROOT'):
        for child in token.children:
          if child.dep_ == 'relcl':
            dec_encrypt = True
          elif child.dep_ == 'prep':
            for child2 in child.children:
              if child2.dep_ == 'pobj':
                for child3 in child2.children:
                  if child3.dep_ == 'relcl':
                    dec_encrypt = True
                  elif child3.dep_ == 'prep':
                    for child4 in child3.children:
                      if child4.dep_ == 'pobj':
                        for child5 in child4.children:
                          if child5.dep_ == 'relcl':
                            dec_encrypt = True

  return dec_encrypt

def get_left_noun(atoken):
  left_edges = set()
  return_left = 0
  for child in atoken.children:
    left_edges.add(child.left_edge.i)
  if len(left_edges)>0: #if token has children
    return_left = min(min(left_edges),atoken.left_edge.i)
  else: #if token has no children
    return_left = atoken.left_edge.i
  return return_left #min(left_edges)

def get_right_noun(atoken):
  right_edges = set()
  return_right = 0
  for child in atoken.children:
    right_edges.add(child.right_edge.i+1)
  if len(right_edges)>0: #if token has children
    return_right = max(max(right_edges),atoken.right_edge.i+1)
  else: #if token has no children
    return_right = atoken.right_edge.i+1
  return return_right #max(right_edges)

def get_right_noun_without_embed(atoken):
  right_edges = set()
  return_right = 0
  for child in atoken.children:
    if child.dep_ == 'prep':
      right_edges.add(child.left_edge.i)
      for child2 in child.children:
        if child2.dep_ == 'pobj':
          right_edges.add(child2.left_edge.i)
          for child3 in child2.children:
            if child3.dep_ == 'relcl':
              right_edges.add(child3.left_edge.i)
            elif child3.dep_ == 'prep':
              right_edges.add(child3.left_edge.i)
              for child4 in child3.children:
                if child4.dep_ == 'pobj':
                  right_edges.add(child4.left_edge.i)
                  for child5 in child4.children:
                    if child5.dep_ == 'relcl':
                      right_edges.add(child4.nbor().left_edge.i)

  if len(right_edges)>0: #if token has children
    return_right = max(right_edges)
  else: #if token has no children
    return_right = atoken.right_edge.i+1
  return return_right #max(right_edges)

def is_indication_clause(text):
  clause_tokens = get_nlp()(text)
  dec_made = False
  for token in clause_tokens:
    if token.dep_ == 'ROOT' and (is_syn_with(token.lemma_, 'indicate') or is_syn_with(token.lemma_, 'means')):
      dec_made = True
  return dec_made

def is_probability_clause(text):

  clause_tokens = get_nlp()(text)
  dec_made = False
  for token in clause_tokens:
    if token.lemma_ and is_syn_with(token.lemma_,'chance') and token.head.dep_ == 'ROOT' and is_syn_with(token.head.lemma_,'is'):
      if token.dep_ == 'attr' or token.dep_ == 'nsubj':
        dec_made = True
  return dec_made

def is_syn_with(phrase,given_phrase):
  if not phrase or not phrase.strip():
    return False
  doc = get_nlp()(phrase)
  # this lemmatizes the noun
  lem_phrase = ''
  names=[]
  for token in doc:
    lem_phrase =token.lemma_
  is_prob = False
  for syn in wordnet.synsets(given_phrase):
    for lemma in syn.lemma_names():
      names.append(lemma)
  if lem_phrase in names:
    is_prob = True
  return is_prob

def get_base(text):
  """
  Extract the base noun phrase from a clause, handling various syntactic structures.
  
  Logic flow:
  1. If clause is indication-type, recursively extract the complement clause
  2. If clause is probability-type, extract the relevant embedded clause
  3. Otherwise, extract subject/attribute based on clause type (equative vs non-equative)
  4. Return simplified base phrase without embedded modifiers
  """
  head_phrase_span = None
  text_tokens = get_nlp()(text)
  
  # Handle indication clauses (e.g., "X indicates that...")
  if is_indication_clause(text):
    for token in text_tokens:
      if token.head.dep_ == 'ROOT' and token.dep_ in ('ccomp'):
        embed_text = ' '.join(atoken.text for atoken in token.subtree)
        return get_base(embed_text.strip())
  
  # Handle probability clauses (e.g., "The chance that...")
  elif is_probability_clause(text):
    for token in text_tokens:
      # Case 1: Extracted as acl (adjectival clause)
      if token.dep_ == 'acl' and token.head.head.dep_ == 'ROOT':
        if token.head.dep_ in ('attr', 'nsubj'):
          embed_text = ' '.join(atoken.text for atoken in token.subtree)
          return get_base(embed_text)
      
      # Case 2: Extracted as relcl (relative clause)
      elif token.dep_ == 'relcl' and is_syn_with(token.head.text, 'chance') and token.head.head.dep_ == 'ROOT':
        embed_text = ' '.join(
          atoken.text for atoken in token.subtree 
          if atoken.i > token.head.i + 1 or atoken.text != 'that'
        )
        return embed_text.strip()
    
    return get_base(embed_text) if embed_text else text
  
  # Handle standard clauses
  else:
    # Non-equative clause: extract subject phrase
    if not is_equative2(text):
      head_phrase_span = None
      left_end = 0
      if not is_there_is_clause(text):
        # Find subject or nominal modifier
        for token in text_tokens:
          if token.dep_ in ('nsubj', 'npadvmod', 'nsubjpass') and token.head.dep_ == 'ROOT':
            # record token for later use in simple base extraction as the head noun in the noun group
            head_token = token
            left_end = get_left_noun(token)
            head_phrase_span = text_tokens[left_end:get_right_noun(token)]
            #print(f"head_phrase: {head_phrase_span.text}", f"head_token: {head_token.text}")
            break
      else: 
        # Handle "there is" clauses by extracting the complement of "there"
        for token in text_tokens:
          if token.dep_ == 'attr' and token.head.dep_ == 'ROOT':
            head_token = token
            left_end = get_left_noun(token)
            head_phrase_span = text_tokens[left_end:get_right_noun(token)]
            #print(f"head_phrase: {head_phrase_span.text}", f"head_token: {head_token.text}")
            break
      
    # Equative clause: extract attribute or subject based on encryption
    else:
      the_dep = ('attr','dobj') if is_encrypting(text) else ('nsubj')
      head_phrase_span = None
      
      for token in text_tokens:
        # record token for later use in simple base extraction as the head noun in the noun group
        head_token = token
        if token.dep_ in the_dep and token.head.dep_ == 'ROOT':
          # Determine right boundary, excluding embedded relative clauses
          right_edge_index = (
            get_right_noun_without_embed(token) 
            if there_is_embedding(token) 
            else token.right_edge.i + 1
          )
          left_token_index = min([t.i for token in token.subtree for t in token.subtree])
          head_phrase_span = text_tokens[left_token_index:right_edge_index]
          print(f"head_phrase: {head_phrase_span.text}", f"head_token: {token.text}")
          break
  
  if head_phrase_span:
    #print(f"Extracted head phrase before simplification: '{head_phrase_span.text}'", f"with head token: '{head_token.text}'")
    result_span = get_base_simple(head_phrase_span, head_token)
    return result_span.text
  else:
    return text
  
def extract_root_noun(noun_phrase):
  """
  Extract the root noun from a noun phrase.
  
  Args:
    noun_phrase: A string containing a noun phrase
    
  Returns:
    The root noun token as a string
  """
  doc = get_nlp()(noun_phrase)
  
  for token in doc:
    if token.dep_ == 'ROOT' or token.head == token:
      return token.text
  
  # Fallback: return the first noun if no ROOT found
  for token in doc:
    if token.pos_ == 'NOUN':
      return token.text
  
  return noun_phrase
  
#text = '27% is the proportion of people aged 31-40 years that tested positive for an illicit drug.'
#nlp = spacy.load('en_core_web_sm')
#text_tokens = nlp(text)
#for token in text_tokens:
#  if token.dep_ == 'attr' and token.text == 'proportion':
#    print(token.text)
#    for child in token.children:
#      print(child.text)

#check that the token has an embedded clause
def there_is_embedding(thetoken):
  the_decision = False
  for descendent in thetoken.subtree:
    if descendent.head != thetoken and descendent.dep_ == 'relcl':
      the_decision = True
  return the_decision
def extract_number_from_noun_phrase(text):
    """
    Extracts the number from a noun phrase like '3667500 people'.
    Returns the number as a string if found, else None.
    """
    doc = get_nlp()(text)
    # Collect consecutive NUM tokens (e.g., '3 667 500')
    num_tokens = []
    for token in doc:
      if token.pos_ == 'NUM':
        num_tokens.append(token)
      elif num_tokens:
        break  # Stop at first non-NUM after a sequence
    if num_tokens:
      # Join all NUM tokens (remove spaces, e.g., '3 667 500' -> '3667500')
      number_str = ''.join(token.text for token in num_tokens)
      # Remove any spaces just in case
      number_str = number_str.replace(' ', '')
      return number_str
    # Fallback: original logic for nummod attached to NOUN
    for token in doc:
      if token.pos_ == 'NUM' and token.dep_ == 'nummod' and token.head.pos_ == 'NOUN':
        return token.text
    # Fallback: if the phrase is just a number
    for token in doc:
      if token.pos_ == 'NUM':
        return token.text
    return None
if __name__ == "__main__":
  #text = "27% is the proportion of people aged 31-40 years that tested positive for an illicit drug."
  #text = "27% of people aged 31-40 years tested positive for an illicit drug."
  #text = "At least 50% of the data is less than or equal to 63"
  #text = "20% of people tested postive for an illicit drug."
  #text = "In 2022, at least twenty percent of the budget that was accounted for was allocated to child protection services."
  #text = "at least twenty percent of the budget that was accounted for"
  #text = "The number 12.5 means that there are 12.5% of 16 300 000 people work in the Manufacturing industry."
  #text = "that there are 12.5 % of 16 300 000 people work in the Manufacturing industry"
  #text = "7.7% is the proportion of the total female population in South Africa in October who were between the ages of 30 and 34."
  text = "the people who were employed"
  #doc = get_nlp()(text)
  #for ent in doc.ents: 
  # print(ent.text, ent.label_) 
  print_pic(text)
  #print(is_equative2(text))
  #print('Base noun phrase:', get_base(text)) 
  #for chunk in doc.noun_chunks:
  #  print('Noun chunk:', chunk.text, chunk.root.text, chunk.root.dep_, chunk.root.head.text)
  #print('get_base:', get_base(text))
  #print('Root noun:', extract_root_noun(get_base(text)))
  #print('simple base noun phrase:', get_base_simple(text))
# Helper to extract number from noun phrase like '3667500 people'



